// Guarded service-worker registration. Never registers in dev/preview/iframe.
// The SW itself is generated by vite-plugin-pwa (generateSW) at /sw.js.
const APP_SW_PATH = "/sw.js";

function shouldRefuse(): { refuse: boolean; killSwitch: boolean } {
  if (typeof window === "undefined") return { refuse: true, killSwitch: false };
  const url = new URL(window.location.href);
  const host = url.hostname;
  const isPreviewHost =
    host.startsWith("id-preview--") ||
    host.startsWith("preview--") ||
    host === "lovableproject.com" ||
    host.endsWith(".lovableproject.com") ||
    host === "lovableproject-dev.com" ||
    host.endsWith(".lovableproject-dev.com") ||
    host === "beta.lovable.dev" ||
    host.endsWith(".beta.lovable.dev");
  const inIframe = window.self !== window.top;
  const killSwitch = url.searchParams.get("sw") === "off";
  const isDev = !import.meta.env.PROD;
  return {
    refuse: isDev || inIframe || isPreviewHost || killSwitch,
    killSwitch,
  };
}

async function unregisterAppSW() {
  if (!("serviceWorker" in navigator)) return;
  try {
    const regs = await navigator.serviceWorker.getRegistrations();
    await Promise.all(
      regs
        .filter((r) => {
          const scriptURL = r.active?.scriptURL || r.installing?.scriptURL || r.waiting?.scriptURL || "";
          return scriptURL.endsWith(APP_SW_PATH);
        })
        .map((r) => r.unregister()),
    );
  } catch { /* noop */ }
}

export function registerServiceWorker() {
  if (typeof window === "undefined") return;
  if (!("serviceWorker" in navigator)) return;

  const { refuse } = shouldRefuse();
  if (refuse) {
    void unregisterAppSW();
    return;
  }

  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register(APP_SW_PATH, { updateViaCache: "none" })
      .catch(() => { /* noop */ });
  });
}
