/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRealizadosRouteImport } from './routes/_authenticated/realizados'
import { Route as AuthenticatedPendientesRouteImport } from './routes/_authenticated/pendientes'
import { Route as AuthenticatedHoyRouteImport } from './routes/_authenticated/hoy'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedGananciasRouteImport } from './routes/_authenticated/ganancias'
import { Route as AuthenticatedCanceladosRouteImport } from './routes/_authenticated/cancelados'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedTrabajoNuevoRouteImport } from './routes/_authenticated/trabajo.nuevo'
import { Route as AuthenticatedTrabajoIdRouteImport } from './routes/_authenticated/trabajo.$id'
import { Route as AuthenticatedAdminTelegramRouteImport } from './routes/_authenticated/admin.telegram'
import { Route as AuthenticatedAdminServiciosRouteImport } from './routes/_authenticated/admin.servicios'
import { Route as AuthenticatedAdminEmpleadosRouteImport } from './routes/_authenticated/admin.empleados'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealizadosRoute = AuthenticatedRealizadosRouteImport.update({
  id: '/realizados',
  path: '/realizados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendientesRoute = AuthenticatedPendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHoyRoute = AuthenticatedHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGananciasRoute = AuthenticatedGananciasRouteImport.update({
  id: '/ganancias',
  path: '/ganancias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanceladosRoute = AuthenticatedCanceladosRouteImport.update({
  id: '/cancelados',
  path: '/cancelados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrabajoNuevoRoute =
  AuthenticatedTrabajoNuevoRouteImport.update({
    id: '/trabajo/nuevo',
    path: '/trabajo/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrabajoIdRoute = AuthenticatedTrabajoIdRouteImport.update({
  id: '/trabajo/$id',
  path: '/trabajo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTelegramRoute =
  AuthenticatedAdminTelegramRouteImport.update({
    id: '/admin/telegram',
    path: '/admin/telegram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServiciosRoute =
  AuthenticatedAdminServiciosRouteImport.update({
    id: '/admin/servicios',
    path: '/admin/servicios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmpleadosRoute =
  AuthenticatedAdminEmpleadosRouteImport.update({
    id: '/admin/empleados',
    path: '/admin/empleados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/cancelados': typeof AuthenticatedCanceladosRoute
  '/ganancias': typeof AuthenticatedGananciasRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/pendientes': typeof AuthenticatedPendientesRoute
  '/realizados': typeof AuthenticatedRealizadosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/empleados': typeof AuthenticatedAdminEmpleadosRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/trabajo/$id': typeof AuthenticatedTrabajoIdRoute
  '/trabajo/nuevo': typeof AuthenticatedTrabajoNuevoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/cancelados': typeof AuthenticatedCanceladosRoute
  '/ganancias': typeof AuthenticatedGananciasRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/pendientes': typeof AuthenticatedPendientesRoute
  '/realizados': typeof AuthenticatedRealizadosRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/empleados': typeof AuthenticatedAdminEmpleadosRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/trabajo/$id': typeof AuthenticatedTrabajoIdRoute
  '/trabajo/nuevo': typeof AuthenticatedTrabajoNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/cancelados': typeof AuthenticatedCanceladosRoute
  '/_authenticated/ganancias': typeof AuthenticatedGananciasRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/hoy': typeof AuthenticatedHoyRoute
  '/_authenticated/pendientes': typeof AuthenticatedPendientesRoute
  '/_authenticated/realizados': typeof AuthenticatedRealizadosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/empleados': typeof AuthenticatedAdminEmpleadosRoute
  '/_authenticated/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/_authenticated/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/_authenticated/trabajo/$id': typeof AuthenticatedTrabajoIdRoute
  '/_authenticated/trabajo/nuevo': typeof AuthenticatedTrabajoNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/cancelados'
    | '/ganancias'
    | '/historial'
    | '/hoy'
    | '/pendientes'
    | '/realizados'
    | '/admin/clientes'
    | '/admin/empleados'
    | '/admin/servicios'
    | '/admin/telegram'
    | '/trabajo/$id'
    | '/trabajo/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ajustes'
    | '/cancelados'
    | '/ganancias'
    | '/historial'
    | '/hoy'
    | '/pendientes'
    | '/realizados'
    | '/'
    | '/admin/clientes'
    | '/admin/empleados'
    | '/admin/servicios'
    | '/admin/telegram'
    | '/trabajo/$id'
    | '/trabajo/nuevo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ajustes'
    | '/_authenticated/cancelados'
    | '/_authenticated/ganancias'
    | '/_authenticated/historial'
    | '/_authenticated/hoy'
    | '/_authenticated/pendientes'
    | '/_authenticated/realizados'
    | '/_authenticated/'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/empleados'
    | '/_authenticated/admin/servicios'
    | '/_authenticated/admin/telegram'
    | '/_authenticated/trabajo/$id'
    | '/_authenticated/trabajo/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/realizados': {
      id: '/_authenticated/realizados'
      path: '/realizados'
      fullPath: '/realizados'
      preLoaderRoute: typeof AuthenticatedRealizadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendientes': {
      id: '/_authenticated/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof AuthenticatedPendientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoy': {
      id: '/_authenticated/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof AuthenticatedHoyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ganancias': {
      id: '/_authenticated/ganancias'
      path: '/ganancias'
      fullPath: '/ganancias'
      preLoaderRoute: typeof AuthenticatedGananciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cancelados': {
      id: '/_authenticated/cancelados'
      path: '/cancelados'
      fullPath: '/cancelados'
      preLoaderRoute: typeof AuthenticatedCanceladosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabajo/nuevo': {
      id: '/_authenticated/trabajo/nuevo'
      path: '/trabajo/nuevo'
      fullPath: '/trabajo/nuevo'
      preLoaderRoute: typeof AuthenticatedTrabajoNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabajo/$id': {
      id: '/_authenticated/trabajo/$id'
      path: '/trabajo/$id'
      fullPath: '/trabajo/$id'
      preLoaderRoute: typeof AuthenticatedTrabajoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/telegram': {
      id: '/_authenticated/admin/telegram'
      path: '/admin/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AuthenticatedAdminTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/servicios': {
      id: '/_authenticated/admin/servicios'
      path: '/admin/servicios'
      fullPath: '/admin/servicios'
      preLoaderRoute: typeof AuthenticatedAdminServiciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/empleados': {
      id: '/_authenticated/admin/empleados'
      path: '/admin/empleados'
      fullPath: '/admin/empleados'
      preLoaderRoute: typeof AuthenticatedAdminEmpleadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedCanceladosRoute: typeof AuthenticatedCanceladosRoute
  AuthenticatedGananciasRoute: typeof AuthenticatedGananciasRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedHoyRoute: typeof AuthenticatedHoyRoute
  AuthenticatedPendientesRoute: typeof AuthenticatedPendientesRoute
  AuthenticatedRealizadosRoute: typeof AuthenticatedRealizadosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminEmpleadosRoute: typeof AuthenticatedAdminEmpleadosRoute
  AuthenticatedAdminServiciosRoute: typeof AuthenticatedAdminServiciosRoute
  AuthenticatedAdminTelegramRoute: typeof AuthenticatedAdminTelegramRoute
  AuthenticatedTrabajoIdRoute: typeof AuthenticatedTrabajoIdRoute
  AuthenticatedTrabajoNuevoRoute: typeof AuthenticatedTrabajoNuevoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedCanceladosRoute: AuthenticatedCanceladosRoute,
  AuthenticatedGananciasRoute: AuthenticatedGananciasRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedHoyRoute: AuthenticatedHoyRoute,
  AuthenticatedPendientesRoute: AuthenticatedPendientesRoute,
  AuthenticatedRealizadosRoute: AuthenticatedRealizadosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminEmpleadosRoute: AuthenticatedAdminEmpleadosRoute,
  AuthenticatedAdminServiciosRoute: AuthenticatedAdminServiciosRoute,
  AuthenticatedAdminTelegramRoute: AuthenticatedAdminTelegramRoute,
  AuthenticatedTrabajoIdRoute: AuthenticatedTrabajoIdRoute,
  AuthenticatedTrabajoNuevoRoute: AuthenticatedTrabajoNuevoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
